# Generated by Django 4.2.5 on 2023-12-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='Онлайн картой', max_length=255),
        ),
    ]
