# Generated by Django 4.2.5 on 2023-12-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default='9999999999999999', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(default='12', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(default='Celery Ananasov', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(default='2025', max_length=4),
        ),
    ]
