# Generated by Django 4.2.5 on 2023-12-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
