# Generated by Django 4.2.5 on 2023-11-27 08:18

import catalog.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderby',
            name='address',
            field=models.CharField(default='Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='city',
            field=models.CharField(default='City', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='email',
            field=models.EmailField(default='Email', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='full_name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='payment_type',
            field=models.CharField(default='cash', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='phone',
            field=models.CharField(default='Phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='products',
            field=models.ManyToManyField(default=catalog.models.Product, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderby',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
