# Generated by Django 4.2.5 on 2023-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('order', '0002_alter_orderby_address_alter_orderby_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderby',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.product'),
        ),
    ]
