# Generated by Django 4.2.5 on 2023-12-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderby_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderby',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='orderby',
            old_name='delivery_type',
            new_name='deliveryType',
        ),
        migrations.RenameField(
            model_name='orderby',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='orderby',
            old_name='payment_type',
            new_name='paymentType',
        ),
        migrations.RenameField(
            model_name='orderby',
            old_name='total_cost',
            new_name='totalCost',
        ),
    ]
